#!/usr/bin/env bash
# Menu of fio jobs

SCRIPT=$(realpath "${BASH_SOURCE[0]}")
SCRIPTPATH=$(dirname "$SCRIPT")

prefill_help="Create a sequential [file] which is [compressible=0] of [size=64M]"
prefill() {
	filename=/tmp/testdata.fio
	compressible=0
	size=64M
	[[ -n $1 ]] && filename=$1
	[[ -n $2 ]] && compressible=$2
	[[ -n $3 ]] && size=$3
	
	[[ $compressible -gt 0 ]] && compopt="--buffer_compress_percentage=$compressible --refill_buffers --buffer_pattern=0xdeadbeef"
	cmd="fio --name=prefill --filename=$filename --size=$size --ioengine=libaio --bs=256k --rw=write --iodepth=1 --numjobs=1 --direct=1 --group_reporting --status-interval=5 $compopt"
	echo $cmd
	$cmd
}




usage() {
    echo "Fio tools"
    echo "---------"
    echo "Usage: $(basename $0) <command> <args>..."
    echo ""
    declare -F | awk '{print $3}' | while read -r funname; do
        help=${funname}_help
        [[ -n ${!help} ]] && echo -e "\t${funname}\t- ${!help}"
    done

    echo ""
    return 0
}



[[ $# -lt 1 ]] && usage && exit
command=${1}
shift
if declare -F | egrep "^declare -f ${command}$" > /dev/null; then
    ${command} "$@" # preserves quoting
else
    echo ERROR: command not found: $command
fi

